# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  format:
    cmds:
      - shfmt -w -i 2 -s **/*.sh
      - chmod +x **/*.sh

  lint:
    cmds:
      - shellcheck **/*.sh

  build:
    cmds:
      - docker build . --tag arranhs/closedbrowser:latest

  build:no-cache:
    cmds:
      - docker build . --tag arranhs/closedbrowser:latest --no-cache

  run:init:
    cmds:
      - mkdir -p ./data

  run:
    deps: [run:init]
    cmds:
      - docker compose up

  run:daemon:
    deps: [run:init]
    cmds:
      - docker compose up -d

  test:
    cmds:
      - task: test:rebrowser
      - task: test:sannysoft
      - task: test:creepjs

  test:rebrowser:
    cmds:
      - ./tests/test-rebrowser.sh

  test:sannysoft:
    cmds:
      - ./tests/test-sannysoft.sh

  test:creepjs:
    cmds:
      - ./tests/test-creepjs.sh
