# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  format:
    cmds:
      - shfmt -w -i 2 -s **/*.sh
      - chmod +x **/*.sh

  lint:
    cmds:
      - shellcheck **/*.sh

  build:
    cmds:
      - docker build . --tag arranhs/closedbrowser:latest

  run:
    cmds:
      - docker compose up

  test:
    cmds:
      - task: test:rebrowser
      - task: test:sannysoft
      - task: test:creepjs

  test:rebrowser:
    cmds:
      - ./tests/test-rebrowser.sh

  test:sannysoft:
    cmds:
      - ./tests/test-sannysoft.sh

  test:creepjs:
    cmds:
      - ./tests/test-creepjs.sh
