name: Build and Push Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - scripts/**
  schedule:
    - cron: "0 2 * * 0" # Every Sunday at 2am
  workflow_dispatch:
    inputs:
      tag:
        description: Custom tag to push
        required: false
        default: ""

env:
  DOCKER_IMAGE: arranhs/closedbrowser

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      browserless: ${{ steps.get-version.outputs.browserless }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version
        id: get-version
        run: |
          BROWSERLESS_VERSION=$(
            grep "^FROM ghcr.io/browserless/chromium" Dockerfile |
            cut -d ':' -f2
          )

          echo "browserless=$BROWSERLESS_VERSION" >> $GITHUB_OUTPUT

          echo "
          Browserless version: $BROWSERLESS_VERSION
          "

  build:
    name: Build Image
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-slug: linux-amd64
          # - runner: ubuntu-24.04-arm
          #   platform: linux/arm64
          #   platform-slug: linux-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Output digest
        uses: GoCodeAlone/github-action-matrix-outputs-write@1.0.3
        with:
          matrix-step-name: build
          matrix-key: ${{ matrix.platform-slug }}
          outputs: |
            digest: ${{ steps.build.outputs.digest }}

  push-tags:
    name: Push Tags
    runs-on: ubuntu-latest
    needs: [get-version, build]
    timeout-minutes: 10

    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get digests
        id: get-digests
        uses: GoCodeAlone/github-action-matrix-outputs-read@1.0.6
        with:
          matrix-step-name: build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push tags
        run: |
          DIGESTS=$(
            echo "$DIGESTS_JSON" |
            jq -r --arg docker_image "$DOCKER_IMAGE" \
              '.digest | to_entries[] | "\($docker_image)@\(.value)"'
          )

          if [ -n "$CUSTOM_TAG" ]; then
            docker buildx imagetools create \
              -t "$DOCKER_IMAGE:$CUSTOM_TAG" \
              $DIGESTS
          else
            docker buildx imagetools create \
              -t "$DOCKER_IMAGE:latest" \
              -t "$DOCKER_IMAGE:$BROWSERLESS_VERSION" \
              $DIGESTS
          fi
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          BROWSERLESS_VERSION: ${{ needs.get-version.outputs.browserless }}
          DIGESTS_JSON: ${{ steps.get-digests.outputs.result }}
          CUSTOM_TAG: ${{ github.event.inputs.tag }}
