name: Update Images

on:
  schedule:
    - cron: "0 1 * * 0" # Every Sunday at 1am
  workflow_dispatch:

jobs:
  update-api:
    name: Update api image
    uses: ahobsonsayers/github-workflows/.github/workflows/docker-update-app-version.yaml@main
    secrets: inherit
    with:
      app-name: Blitzbrowser
      dockerfile: api.dockerfile
      version-arg: BLITZBROWSER_DIGEST
      version-source: docker-digest
      version-source-docker-image: ghcr.io/blitzbrowser/blitzbrowser:latest

  update-app:
    name: Update app image
    uses: ahobsonsayers/github-workflows/.github/workflows/docker-update-app-version.yaml@main
    secrets: inherit
    with:
      app-name: Blitzbrowser Dashboard
      dockerfile: app.dockerfile
      version-arg: BLITZBROWSER_COMMIT
      version-source: github-commit
      version-source-github-repo: blitzbrowser/blitzbrowser
